BICHOS = {
    1: "Avestruz",
    2: "Águia",
    3: "Burro",
    4: "Borboleta",
    5: "Cachorro",
    6: "Cabra",
    7: "Camelo",
    8: "Cobra",
    9: "Coelho",
    10: "Cavalo",
    11: "Elefante",
    12: "Gato",
    13: "Jacaré",
    14: "Leão",
    15: "Macaco",
    16: "Tartaruga",
    17: "Touro",
    18: "Galo",
    19: "Lobo",
    20: "Carneiro",
    21: "Pavão",
    22: "Pombo",
    23: "Tigre",
    24: "Urso",
    25: "Vaca",
}
